name = "TestStdlibs"
uuid = "01174299-f219-4c19-97eb-1ab801131281"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Markdown", "Jive"]
