name = "TestStdlibs"
uuid = "01174299-f219-4c19-97eb-1ab801131281"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Dates", "Distributed", "InteractiveUtils", "LinearAlgebra", "Libdl", "Markdown", "Printf", "Profile",
        "REPL", "Random", "SparseArrays", "SharedArrays", "Statistics", "Test", "Unicode", "UUIDs",
        "Jive"]
